apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: hello-rpilab-config
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"hello-rpilab","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web"},"name":"hello-rpilab","namespace":"aro"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"env":[{"name":"SPRING_CONFIG_IMPORT","value":"optional:configtree:${SERVICE_BINDING_ROOT}/config/"}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/maxScale":"3","autoscaling.knative.dev/minScale":"0","autoscaling.knative.dev/window":"120s","sidecar.opentelemetry.io/inject":"true"}},{"name":"testing_pipeline_matching_labels","value":{"apps.tanzu.vmware.com/language":"java","apps.tanzu.vmware.com/pipeline":"test"}},{"name":"gitops_server_address","value":"https://github.com"},{"name":"gitops_repository_owner","value":"alexandreroman"},{"name":"gitops_repository_name","value":"rpilab-tap"}],"resources":{"limits":{"memory":"1Gi"},"requests":{"cpu":"500m","memory":"1Gi"}},"serviceClaims":[{"name":"config","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"hello-rpilab-config"}},{"name":"db","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ClassClaim","name":"hello-rpilab-db"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/alexandreroman/hello-rpilab"}}}}
    local-source-proxy.apps.tanzu.vmware.com: tdkhub.azurecr.io/tanzu-application-platform/dev/workload:aro-hello-rpilab@sha256:2961912381c39e59ede90d519d45f09df305dc685a9aeb77a5c61930a63315bd
    autoscaling.knative.dev/maxScale: "3"
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/window: 120s
    sidecar.opentelemetry.io/inject: "true"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: hello-rpilab
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: hello-rpilab
spec:
  name: config
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: hello-rpilab-config
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: hello-rpilab
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: hello-rpilab-db
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"hello-rpilab","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"web"},"name":"hello-rpilab","namespace":"aro"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"17"}]},"env":[{"name":"SPRING_CONFIG_IMPORT","value":"optional:configtree:${SERVICE_BINDING_ROOT}/config/"}],"params":[{"name":"annotations","value":{"autoscaling.knative.dev/maxScale":"3","autoscaling.knative.dev/minScale":"0","autoscaling.knative.dev/window":"120s","sidecar.opentelemetry.io/inject":"true"}},{"name":"testing_pipeline_matching_labels","value":{"apps.tanzu.vmware.com/language":"java","apps.tanzu.vmware.com/pipeline":"test"}},{"name":"gitops_server_address","value":"https://github.com"},{"name":"gitops_repository_owner","value":"alexandreroman"},{"name":"gitops_repository_name","value":"rpilab-tap"}],"resources":{"limits":{"memory":"1Gi"},"requests":{"cpu":"500m","memory":"1Gi"}},"serviceClaims":[{"name":"config","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ResourceClaim","name":"hello-rpilab-config"}},{"name":"db","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ClassClaim","name":"hello-rpilab-db"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/alexandreroman/hello-rpilab"}}}}
    local-source-proxy.apps.tanzu.vmware.com: tdkhub.azurecr.io/tanzu-application-platform/dev/workload:aro-hello-rpilab@sha256:2961912381c39e59ede90d519d45f09df305dc685a9aeb77a5c61930a63315bd
    autoscaling.knative.dev/maxScale: "3"
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/window: 120s
    sidecar.opentelemetry.io/inject: "true"
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: hello-rpilab
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: hello-rpilab
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ClassClaim
    name: hello-rpilab-db
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: hello-rpilab

